name: frontend
on: 
  push:
    paths:
      - .github/workflows/frontend.yaml
      - flake.*
      - nix/**
      - frontend/**
defaults:
  run:
    working-directory: frontend/
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - name: Build Nix
        run: nix build ../\#devShells.x86_64-linux.frontend
      - name: Install Dependencies
        run: nix develop ../\#devShells.x86_64-linux.frontend --command pnpm install
      - name: Typecheck
        if: success() || failure()
        run: nix develop ../\#devShells.x86_64-linux.frontend --command make typecheck
      - name: Test
        if: success() || failure()
        run: nix develop ../\#devShells.x86_64-linux.frontend --command make test
      - name: Lintcheck
        if: success() || failure()
        run: nix develop ../\#devShells.x86_64-linux.frontend --command make lintcheck
  visual:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - name: Build Nix
        run: nix build ../\#devShells.x86_64-linux.frontend
      - name: Install Dependencies
        run: nix develop ../\#devShells.x86_64-linux.frontend --command pnpm install
      - name: Visual Tests
        if: success() || failure()
        run: nix develop ../\#devShells.x86_64-linux.frontend --command make test-visual
